### ISSUE TITLE
GetRandomNumber() causes crash in ch6

### ISSUE THREAD

**Issue by Theswweet** [MyLegGuy/Higurashi-Vita#22]
> void main()
> {
> 	char	rn_Iri_Def1;
> 	char	rn_Iri_Def2;
> 	char	rn_Iri_Warai;
> 	char	rn_Iri_Majime;
> 	char	rn_Iri_Majime2;
> 
> 	int	i;
> 	i = GetRandomNumber( 3 );
> 	if(i == 0)
> 	{
> 		rn_Iri_Def1 = "Iri_Def1#";	rn_Iri_Def2 = "Iri_Def2#";	rn_Iri_Warai = "Iri_Warai#";
> 		rn_Iri_Majime = "Iri_Majime#";	rn_Iri_Majime2 = "Iri_Majime2#";
> 	}
> 	if(i == 1)
> 	{
> 	rn_Iri_Def1 = "Iri_Def1!";	rn_Iri_Def2 = "Iri_Def2!";	rn_Iri_Warai = "Iri_Warai!";
> 		rn_Iri_Majime = "Iri_Majime!";	rn_Iri_Majime2 = "Iri_Majime2!";
> 	}
> 	if(i == 2)
> 	{
> 		rn_Iri_Def1 = "Iri_Def1+";	rn_Iri_Def2 = "Iri_Def2+";	rn_Iri_Warai = "Iri_Warai+";
> 		rn_Iri_Majime = "Iri_Majime+";	rn_Iri_Majime2 = "Iri_Majime2+";
> 	}

This seems to only be used once - in Day 3-3 - and the game rolls a random number to see which of Irie's three outfits will be used for his portraits for the scene.

Current workaround - replace any instances of rn_iri_majime (and etc) called, with one of the 3 sets of portraits.

Thankfully the GetRandomNumber() function isn't used elsewhere in Chapter 6, a quick search shows.

**Comment by MyLegGuy** [comment]
I will get a copy of chapter 8 and look at the new functions added in that game.
I'll implement whatever new functions are needed and set the rest to be ignored.
These reports are useful because I'll know which functions I need to implement *for sure* and where to find examples of them.

**Comment by MyLegGuy** [comment]
i've implemented this function. it will be in the next build I upload, soon.

here's a fun fact for you.
i was looking at how chapter 8 does GetRandomNumber.
for GetRandomNumber(3), a random number between 0 (inclusive) and 2 (inclusive) is generated.
this unity function is used: https://docs.unity3d.com/ScriptReference/Random.Range.html
the number generated does not have to be a whole number, and probably won't be.
the number is rounded down before being given to the script.
examples of numbers generated that would yield zero: 0, 0.1, 0.001, 0.2, 0.02, 0.0002, 0.3...
examples of numbers generated that would yield one: 1, 1.1, 1.0001, 1.4, 1.6, 1.2, 1.002...
examples of numbers generated that would yield two: 2.
that's right. while there are pretty much infinite ways to get 0 and 1, there is exactly one way to get 2.
therefore, the chance of generating 2 is essentially 0. even if 100,000 people have played chapter 6, it's likely that none of them have had 2 generated.

because this was the only instance out of all the games I could find that uses GetRandomNumber, I decided to "fix" it for my engine.

**Comment by Theswweet** [comment]
I still have the issue, after testing it with the latest vpk. Here's the error that I get on 3-3 atm.
![2020-06-23-231705](https://user-images.githubusercontent.com/5161970/85508511-14208f00-b5a9-11ea-9afe-629c1b8bba26.png)

**Comment by MyLegGuy** [comment]
okay, so the fix is to just change all instances of "char" in:
```
char rn_Iri_Def1;
char rn_Iri_Def2;
char rn_Iri_Warai;
char rn_Iri_Majime;
char rn_Iri_Majime2;
```
to "local".
I made the game converter do it automatically. If you'd prefer to just convert the game instead of fixing it manually: 
[HigurashiVitaConverter-06-25-20.zip](https://github.com/MyLegGuy/Higurashi-Vita/files/4829192/HigurashiVitaConverter-06-25-20.zip)

I don't know how these variables (rn_Iri_Def1, rn_Iri_Def2, rn_Iri_Warai,rn_Iri_Majime, etc...) could possibly be used to change an image. They can't refer to a filename because I think "+", "!" and "#" are all illegal filename characters.
So I guess the script probably uses more code for this?
Well, if it somehow works, then I won't worry about it at all.

**Comment by Theswweet** [comment]
I'll test, but just an fyi - these aren't illegal filenames, that's really what they're called in streamingassets/CG.

**Comment by Theswweet** [comment]
Fixed with latest conversion tool.
